
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 18 22:57:27 CST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 8;
  public static final int Parentesis_c = 24;
  public static final int For = 11;
  public static final int Parentesis_a = 23;
  public static final int Suma = 13;
  public static final int Numero = 32;
  public static final int Corchete_c = 28;
  public static final int Op_booleano = 22;
  public static final int ERROR = 33;
  public static final int Corchete_a = 27;
  public static final int Identificador = 31;
  public static final int Comillas = 3;
  public static final int Int = 5;
  public static final int Llave_c = 26;
  public static final int Llave_a = 25;
  public static final int Op_relacional = 19;
  public static final int P_coma = 30;
  public static final int T_dato = 4;
  public static final int Main = 29;
  public static final int Cadena = 6;
  public static final int EOF = 0;
  public static final int Division = 16;
  public static final int Op_incremento = 21;
  public static final int Op_atribucion = 20;
  public static final int Resta = 14;
  public static final int If = 7;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Op_logico = 18;
  public static final int Modulo = 17;
  public static final int Do = 9;
  public static final int Igual = 12;
  public static final int While = 10;
  public static final int Multiplicacion = 15;
}

